#!/usr/bin/env ruby
# frozen_string_literal: true

require 'aaq'
require 'optparse'

Version = AAQ::VERSION

opt = OptionParser.new
opt.banner = 'Usage: bundle exec aaq [image] [--color]'
opt.on('--color', 'output color ascii-art')
args = opt.parse(ARGV)

if args.empty?
  puts opt.help
else
  eval AAQ::AAQ.new(args[0]).convert.to_s
end
