#!/usr/bin/env ruby
# frozen_string_literal: true

require 'aaq'
require 'optparse'

Version = AAQ::VERSION

options = {}
opt = OptionParser.new do |o|
  o.banner = 'Usage: bundle exec aaq [image] [--color]'
  o.on('--color', 'Output color ascii-art')
  o.on('--horizontal N', Integer, 'Number of horizontal pixels per character (default: 6)') do |n|
    options[:horizontal] = n
  end
  o.on('--vertical N', Integer, 'Number of vertical pixels per character (default: 16)') do |n|
    options[:vertical] = n
  end
end

args = opt.parse(ARGV)
if args.empty?
  puts opt.help
  exit
end

begin
  eval AAQ::AAQ.new(
    args.first,
    options: {
      unit_horizontal: options[:horizontal],
      unit_vertical: options[:vertical]
    }
  ).convert.to_s
rescue SyntaxError
  warn 'Error: The output ascii art is too small to generate the complete code.'
  warn 'A smaller value for the --horizontal or --vertical options might remove the error.'
end
